services:

  backend:
    image: ghcr.io/m0wer/rssfilter-backend:master
    container_name: rssfilter-backend
    build:
      context: backend
      target: dev
    environment:
      API_BASE_URL: "http://localhost:${PROXY_PORT:-3000}"
      ROOT_PATH: "/api"
    volumes:
      - ./backend/src:/app/src
    labels:
      traefik.http.routers.backend.entrypoints: web
      traefik.http.routers.backend.rule: PathPrefix(`/api`)
      traefik.http.routers.backend.service: backend
      traefik.http.services.backend.loadbalancer.server.port: 80

  frontend:
    image: ghcr.io/m0wer/rssfilter-frontend:master
    container_name: rssfilter-frontend
    build:
      context: frontend
      target: dev
    environment:
      API_BASE_URL: "http://localhost:${PROXY_PORT:-3000}/api/v1/"
    # FIXME: this is so requests to /health and /host-config work on localhost
    # for any port
    ports:
      - 8501:8501
    labels:
      traefik.http.routers.frontend.entrypoints: web
      traefik.http.routers.frontend.rule: PathPrefix(`/`)
      traefik.http.routers.frontend.service: frontend
      traefik.http.services.frontend.loadbalancer.server.port: 8501

  proxy:
    image: traefik:v2.3
    hostname: traefik
    command:
     - --providers.docker
     - --entryPoints.web.address=:80
     - --entryPoints.web.forwardedHeaders.insecure
    ports:
      - ${PROXY_PORT:-3000}:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
