"""init

Revision ID: 66db43bbbd2b
Revises:
Create Date: 2024-03-25 22:06:42.836600

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "66db43bbbd2b"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "feed",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("url", sqlmodel.sql.sqltypes.AutoString(), nullable=False),  # type: ignore[attr-defined]
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),  # type: ignore[attr-defined]
        sa.Column("logo", sqlmodel.sql.sqltypes.AutoString(), nullable=True),  # type: ignore[attr-defined]
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=False),  # type: ignore[attr-defined]
        sa.Column("language", sqlmodel.sql.sqltypes.AutoString(), nullable=True),  # type: ignore[attr-defined]
        sa.Column("updated", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("url"),
    )
    op.create_table(
        "user",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),  # type: ignore[attr-defined]
        sa.Column("first_request", sa.DateTime(), nullable=False),
        sa.Column("last_request", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "article",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),  # type: ignore[attr-defined]
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=False),  # type: ignore[attr-defined]
        sa.Column("url", sqlmodel.sql.sqltypes.AutoString(), nullable=False),  # type: ignore[attr-defined]
        sa.Column("comments_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),  # type: ignore[attr-defined]
        sa.Column("pub_date", sa.DateTime(), nullable=True),
        sa.Column("updated", sa.DateTime(), nullable=False),
        sa.Column("embedding", sqlmodel.sql.sqltypes.AutoString(), nullable=True),  # type: ignore[attr-defined]
        sa.Column("feed_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["feed_id"],
            ["feed.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("url", "feed_id"),
    )
    op.create_index(op.f("ix_article_feed_id"), "article", ["feed_id"], unique=False)
    op.create_index(op.f("ix_article_url"), "article", ["url"], unique=False)
    op.create_table(
        "userfeedlink",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("feed_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["feed_id"],
            ["feed.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "feed_id"),
    )
    op.create_table(
        "userarticlelink",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("article_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["article_id"],
            ["article.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "article_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("userarticlelink")
    op.drop_table("userfeedlink")
    op.drop_index(op.f("ix_article_url"), table_name="article")
    op.drop_index(op.f("ix_article_feed_id"), table_name="article")
    op.drop_table("article")
    op.drop_table("user")
    op.drop_table("feed")
    # ### end Alembic commands ###
